### ISSUE TITLE
Add explicit reCaptcha 2 check to contact form

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Site-Web-App-ETS#13]
Afin de pouvoir mieux supprimer ces robots qui affectent notre workflow. 🤖 

Lien pour l'info:
https://www.netlify.com/docs/form-handling/#spam-filtering

**Comment by kovy42** [comment]
J'ai ajouté un captcha explicite et une entrée "honeypot". Les robots ne devraient plus être une menace 🤖

**Comment by zaclimon** [comment]
Nice! Est-ce que tu pourrais regarder les commentaires que j'ai laissé? Une fois réglé, ça devrait être correct pour un push en production.

**Comment by zaclimon** [comment]
Bon suite à un bug soulevé dans #12 un seul champ a été ajouté pour le formulaire de contact. Netlify a été contacté de la situation et voici ce qu'ils m'ont répondu:

> You've run into a known issue where our build-in explicit recaptcha is only able to handle one recaptcha per page. I've added you to the bug report so that you will get notified when we get that fixed. 
>
> In the meantime, and as you suspected, you can try implementing a custom recaptcha with your own settings as mentioned here: https://www.netlify.com/docs/form-handling/#custom-receptcha-2-with-your-own-settings.

On va laisser l'issue ouverte histoire de faire du suivi par la suite.

**Comment by LouisPhilippeHeon** [comment]
On va retirer cette page, plutôt que de faire un form on va laisser notre courriel, ça ne sera plus un problème
