### ISSUE TITLE
Long loading time for team members image

### ISSUE THREAD

**Issue by lol3909** [ApplETS/Site-Web-App-ETS#74]
**Describe the bug**
In the team [members page](https://clubapplets.ca/equipe) are taking a while to load.
**To Reproduce**
1. Clear browser cache to simulate a first visit.
2. Go to https://clubapplets.ca/equipe
3. Wait and check Xavier Paquet-Rapold picture.

**Expected behavior**
The image should load a bit faster.

**Proposal**
Change the images to [webp](https://developers.google.com/speed/webp?hl=fr) to have more light weight images.

**Screenshots**
![chrome-capture-2023-6-16 (1)](https://github.com/ApplETS/Site-Web-App-ETS/assets/33705515/4346fff5-0fff-4464-9ecc-e206fcf72253)

**Comment by XavierPaquet-Rapold** [comment]
I Will reduce the image resolution
